# Generated by Django 5.2.3 on 2025-06-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.CharField(default='placeholder-clerk-id', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='placeholder-clerk-id', max_length=255),
            preserve_default=False,
        ),
    ]
