# Generated by Django 5.2.3 on 2025-06-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cart_user_remove_order_user_cart_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='clerk_user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='clerk_user_id',
        ),
    ]
