# Generated by Django 5.2.3 on 2025-06-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_user_id_cart_clerk_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
