# Generated by Django 5.2.3 on 2025-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_stripe_checkout_id_order_stripe_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
