# Generated by Django 5.2.3 on 2025-07-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='subtotal',
        ),
    ]
