# Generated by Django 5.2.3 on 2025-07-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
