# Generated by Django 5.2.3 on 2025-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
