# Generated by Django 5.2.3 on 2025-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_shipping_label_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arcel_width',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel_height',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel_length',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_rate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
