# Generated by Django 5.2.3 on 2025-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_arcel_width_order_parcel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippo_shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
